import node0 from './blend/node.ts';
import node1 from './field/node.ts';
import node2 from './flow/node.ts';
import node3 from './fractal/node.ts';
import node4 from './give/node.ts';
import node5 from './grade/node.ts';
import node6 from './lens/node.ts';
import node7 from './light/node.ts';
import node8 from './math/node.ts';
import node9 from './out/node.ts';
import node10 from './paint/node.ts';
import node11 from './place/node.ts';
import node12 from './playback/node.ts';
import node13 from './point/node.ts';
import node14 from './polar/node.ts';
import node15 from './song/node.ts';
import node16 from './source/node.ts';
import node17 from './spread/node.ts';
import node18 from './take/node.ts';
import node19 from './track/node.ts';
import node20 from './tracks/node.ts';
import node21 from './value/node.ts';
import node22 from './video/node.ts';
import node23 from './wave/node.ts';
import { NODE_FAMILY_DETAILS, type NodeFamily } from './descriptor.ts';

// Generated by tools/generate-nodes.ts. Add a folder containing node.ts; do not
// edit this list by hand. Static imports keep the browser bundle deterministic
// while the generator gives Node, Vite, tests, and the MCP server one discovery path.
export const NODE_DEFINITIONS = [
  node0,
  node1,
  node2,
  node3,
  node4,
  node5,
  node6,
  node7,
  node8,
  node9,
  node10,
  node11,
  node12,
  node13,
  node14,
  node15,
  node16,
  node17,
  node18,
  node19,
  node20,
  node21,
  node22,
  node23,
] as const;

export type NodeKind = (typeof NODE_DEFINITIONS)[number]['kind'];
export type NodeDefinition = (typeof NODE_DEFINITIONS)[number];

export const NODE_KINDS = NODE_DEFINITIONS.map((node) => node.kind) as NodeKind[];

export const NODE_BY_KIND = Object.fromEntries(
  NODE_DEFINITIONS.map((node) => [node.kind, node]),
) as { [Kind in NodeKind]: Extract<NodeDefinition, { kind: Kind }> };

const FAMILY_ORDER = Object.keys(NODE_FAMILY_DETAILS) as NodeFamily[];

export const NODE_FAMILIES = FAMILY_ORDER.map((name) => ({
  name,
  about: NODE_FAMILY_DETAILS[name],
  kinds: NODE_DEFINITIONS.filter((node) => node.family === name)
    .sort((a, b) => a.order - b.order)
    .map((node) => node.kind),
}));

export const BROWSABLE_NODE_DEFINITIONS = NODE_FAMILIES.flatMap((family) =>
  family.kinds
    .map((kind) => NODE_BY_KIND[kind])
    .filter((node) => node.browser === 'node' || node.browser === 'modes'),
);
