import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const nodes = path.resolve(here, '../client/nodes');
const target = path.join(nodes, 'generated.ts');

function source(): string {
  const names = fs
    .readdirSync(nodes, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && fs.existsSync(path.join(nodes, entry.name, 'node.ts')))
    .map((entry) => entry.name)
    .sort();
  if (names.length === 0) throw new Error('no node folders found');

  const imports = names.map((name, index) => `import node${index} from './${name}/node.ts';`);
  const members = names.map((_name, index) => `  node${index},`);
  return `${imports.join('\n')}
import { NODE_FAMILY_DETAILS, type NodeFamily } from './descriptor.ts';

// Generated by tools/generate-nodes.ts. Add a folder containing node.ts; do not
// edit this list by hand. Static imports keep the browser bundle deterministic
// while the generator gives Node, Vite, tests, and the MCP server one discovery path.
export const NODE_DEFINITIONS = [
${members.join('\n')}
] as const;

export type NodeKind = (typeof NODE_DEFINITIONS)[number]['kind'];
export type NodeDefinition = (typeof NODE_DEFINITIONS)[number];

export const NODE_KINDS = NODE_DEFINITIONS.map((node) => node.kind) as NodeKind[];

export const NODE_BY_KIND = Object.fromEntries(
  NODE_DEFINITIONS.map((node) => [node.kind, node]),
) as { [Kind in NodeKind]: Extract<NodeDefinition, { kind: Kind }> };

const FAMILY_ORDER = Object.keys(NODE_FAMILY_DETAILS) as NodeFamily[];

export const NODE_FAMILIES = FAMILY_ORDER.map((name) => ({
  name,
  about: NODE_FAMILY_DETAILS[name],
  kinds: NODE_DEFINITIONS.filter((node) => node.family === name)
    .sort((a, b) => a.order - b.order)
    .map((node) => node.kind),
}));

export const BROWSABLE_NODE_DEFINITIONS = NODE_FAMILIES.flatMap((family) =>
  family.kinds
    .map((kind) => NODE_BY_KIND[kind])
    .filter((node) => node.browser === 'node' || node.browser === 'modes'),
);
`;
}

export function generateNodes(check = false): void {
  const next = source();
  const held = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (check) {
    if (held !== next) throw new Error('client/nodes/generated.ts is stale; run npm run nodes');
    return;
  }
  if (held !== next) fs.writeFileSync(target, next);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateNodes(process.argv.includes('--check'));
}
